# Generated by Django 2.2.3 on 2019-10-04 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191004_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweeter',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='tweeter',
            name='time_joined',
        ),
    ]
