# Generated by Django 2.2.3 on 2019-10-06 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191004_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweeter',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=6022)),
                ('dislike', models.IntegerField(default=8441)),
                ('file_name', models.CharField(default='', max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='app.Tweeter')),
            ],
        ),
    ]
