# Generated by Django 2.2.3 on 2019-10-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191007_0531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='tweeter',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tweeter',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='post',
            name='dislikes',
            field=models.IntegerField(default=5171),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=2981),
        ),
    ]
