# Generated by Django 2.2.3 on 2019-10-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191007_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweeter',
            name='profile_pic_path',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='dislikes',
            field=models.IntegerField(default=685),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=4790),
        ),
    ]
